### ISSUE TITLE
Recommended install command not secure for internet accessable docker containers

### ISSUE THREAD

**Issue by dennis1248** [mjarkk/docker-lemp-config#1]
I recommend changing `docker-compose build && docker-compose up -d && chmod 777 html -R` to `docker-compose build && docker-compose up -d && chmod 775 html -R` to remove write permissions for non owner and in-group users. 

Besides this I also recommend adding `chown $USER -R html` to make sure the folder and files are not owned by root.

`docker-compose build && docker-compose up -d && chmod 775 html -R && chown $USER -R html`

**Comment by mjarkk** [comment]
Fixed it :)
